packages:
  - apps/*
  - packages/*

nodeLinker: hoisted

onlyBuiltDependencies:
  - esbuild
  - "@sentry/cli"
  - sharp
  - "@op-engineering/op-sqlite"

peerDependencyRules:
  allowedVersions:
    typescript: "6"
