import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ThemeProvider } from "next-themes";
import type { FC } from "react";
import { RouterAdapter } from "./_components/router-adapter";
import "./globals.css";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
} satisfies Metadata;

const Layout: FC<LayoutProps<"/">> = async (props) => {
	return (
		// next-themesがクライアント側でclass属性を追加するためハイドレーション警告を抑制
		// https://github.com/pacocoursey/next-themes#with-app
		<html lang="ja" suppressHydrationWarning>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<ThemeProvider attribute="class" defaultTheme="system" enableSystem>
					<RouterAdapter>{props.children}</RouterAdapter>
				</ThemeProvider>
			</body>
		</html>
	);
};

export default Layout;
