name: Chromatic

on:
  pull_request:
    types: [opened, reopened, synchronize, labeled]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  chromatic:
    name: Run Chromatic
    runs-on: ubuntu-latest
    timeout-minutes: 15
    if: contains(github.event.pull_request.labels.*.name, 'with-storybook')
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0

      - name: Setup workspace
        uses: ./.github/actions/setup-workspace

      - name: Run Chromatic
        env:
          CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
        run: pnpm --filter @next-lift/react-components chromatic
