name: Consistent Pull Request

on:
  pull_request:
    types: [opened, edited, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  consistent-pull-request:
    name: Consistent Pull Request
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check head branch name
        id: check-head-branch-name
        uses: praha-inc/action-restrict-head-branch@48b7777bbd99e4702abe38e4a996fcd5a2453667 # v1.0.0
        with:
          rules: |
            feature/**/* bugfix/**/* refactor/**/* infra/**/* chore/**/* deps/**/* docs/**/* improve/**/*

      - name: Check base branch name
        uses: praha-inc/action-restrict-base-branch@d0c225fdd8eab6e1e4b4e455e0877003c33078a2 # v1.0.2
        with:
          rules: |
            main <- feature/**/* bugfix/**/* refactor/**/* infra/**/* chore/**/* deps/**/* docs/**/* improve/**/*

      - name: Check pr label name
        if: always() && steps.check-head-branch-name.conclusion == 'success'
        uses: praha-inc/action-restrict-pr-label@7afc265323238e3b73f016e565f9c81d5e67362d # v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          rules: |
            ** <- feature/**/* [feature]
            ** <- bugfix/**/* [bugfix]
            ** <- refactor/**/* [refactor]
            ** <- infra/**/* [infra]
            ** <- chore/**/* [chore]
            ** <- deps/**/* [deps]
            ** <- docs/**/* [docs]
            ** <- improve/**/* [improve]
